### ISSUE TITLE
Support Apollo Client 2.0

### ISSUE THREAD

**Issue by dallonf** [lucasconstantino/apollo-cache#4]
As of Apollo Client 2.0, there is still a need for this library, but it doesn't seem to invalidate the cache anymore.

I might be able to investigate deeper if I have time, although if it's particularly difficult, I might consider PRing something to Apollo Client itself...

**Comment by lucasconstantino** [comment]
@dallonf thanks for the heads up. I haven't been working with this project for some time, though I know the necessity is relevant. I'll see if I find the time to make it work with Apollo 2.0
